version: '3.8'

services:
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: study_backend!
    ports:
      - "5011:3306"
    volumes:
      - "./mysql-data/user:/var/lib/mysql"
    networks:
      - msa-network

networks:
  msa-network: